markdown: redcarpet
pygments: true
paginate: 8

safe:  false

#Site config
title: 80aj_Coder_Chinese_Shanghai
description: Chinese 80s Coder, only for php ,java , desifgn
keywords: Jekyll Theme
url: http://blog.80aj.com
feed: /atom.xml
favicon: http://blog.80aj.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: 清月 张
    email: cfrs2005@gmail.com
    imageLink: http://tp4.sinaimg.cn/1884018943/180/40033761017/1
    simpleIntro: 普通Coder
    detailIntro:
      <p>Jekyll 是一个简洁的、特别针对博客平台的 静态网站 生成器。它使用一个模板目录作为网站布局的基础框架，并在其上运行 Textile 、 Markdown 或 Liquid 标记语言的转换器，最终生成一个完整的静态Web站点，可以被放置在Apache或者你喜欢的其他任何Web服务器上。它同时也是 GitHub Pages 、一个由 GitHub 提供的用于托管项目主页或博客的服务，在后台所运行的引擎。</p>
      <p>很早之前，使用过 wordpress 来写博客。但是还要处理很多的底层问题。而使用 Jekyll 来写博客，可以很简单，写 Markdown 就好。然而，Jekyll 还很年轻，没有很多主题的支持。这里的主题，就是为 Jekyll 而写的。希望你能喜欢。</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/pizn
  - class: icon-renren
    url: http://renren.com
  - class: icon-github-alt
    url: http://github.com/pizn
  - class: icon-twitter
    url: http://twitter.com/piznlin
  - class: icon-google-plus
    url: http://google.com

#Links
customLinks:
  - item:
    - text: 安静
      url: http://www.80aj.com
    - text: 乐蛙
      url: http://www.lewaos.com
    - text: 好孩子
      url: http://www.goodbaby.com
    message: Friends
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: Google Font
      url: http://www.google.com/fonts/
    - text: jQuery
      url: http://jquery.com/
    message: 其他相关链接

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  id: UA-40169250-1

#comment config
disqus:
  config: false
  id: piznblog

duoshuo:
  config: true
  id: zhanxin